// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj6RbT7ibDvEV_ZjeS5iO9_0e0USgmXFg',
    appId: '1:1076369172527:web:86c45fd25867e3d2803eda',
    messagingSenderId: '1076369172527',
    projectId: 'v-connect-eac00',
    authDomain: 'v-connect-eac00.firebaseapp.com',
    storageBucket: 'v-connect-eac00.firebasestorage.app',
    measurementId: 'G-290QTP28Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwpKUt2HwrHGZOEJWMElMWCxbdkkA3pA',
    appId: '1:1076369172527:android:c78d21eb0ea442c0803eda',
    messagingSenderId: '1076369172527',
    projectId: 'v-connect-eac00',
    storageBucket: 'v-connect-eac00.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkWEJTiuJklJmdOdNAVE_NCDDNSi_ekM',
    appId: '1:1076369172527:ios:8ff4e621d82c799e803eda',
    messagingSenderId: '1076369172527',
    projectId: 'v-connect-eac00',
    storageBucket: 'v-connect-eac00.firebasestorage.app',
    iosBundleId: 'com.example.vComm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUkWEJTiuJklJmdOdNAVE_NCDDNSi_ekM',
    appId: '1:1076369172527:ios:8ff4e621d82c799e803eda',
    messagingSenderId: '1076369172527',
    projectId: 'v-connect-eac00',
    storageBucket: 'v-connect-eac00.firebasestorage.app',
    iosBundleId: 'com.example.vComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj6RbT7ibDvEV_ZjeS5iO9_0e0USgmXFg',
    appId: '1:1076369172527:web:76d5364a2b1b9f8b803eda',
    messagingSenderId: '1076369172527',
    projectId: 'v-connect-eac00',
    authDomain: 'v-connect-eac00.firebaseapp.com',
    storageBucket: 'v-connect-eac00.firebasestorage.app',
    measurementId: 'G-6Y3SCDEKQD',
  );
}
